name: ride_metric_x
description: "RideMetricX – cross-platform motorcycle suspension tuning simulator."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  archive: ^4.0.0
  file_picker: ^10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  fake_async: ^1.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/front_imu_sample.csv
    - assets/data/rear_imu_sample.csv
