import 'suspension_parameters.dart';

/// Severity level of a [Recommendation], used for prioritisation.
enum RecommendationSeverity {
  /// Minor improvement suggested.
  low,

  /// Noticeable issue that should be addressed.
  medium,

  /// Significant issue that requires prompt attention.
  high;

  /// Numeric score used for descending sort (high → medium → low).
  int get priorityScore => index; // low=0, medium=1, high=2
}

/// Category of a [Recommendation].
enum RecommendationType {
  /// Suspension is bottoming out too frequently.
  bottomingTooMuch,

  /// Suspension is not reaching sufficient travel.
  notUsingFullTravel,

  /// Ride quality is harsh due to high-frequency vibrations.
  harshRide,

  /// Excessive rebound causing oscillations or slow settlement.
  tooMuchRebound,

  /// Front and rear suspension travel usage is significantly imbalanced.
  imbalancedFrontRear,
}

/// A single actionable suggestion generated by [RecommendationEngine].
///
/// Each recommendation carries a [severity] for prioritisation, human-readable
/// [title] and [rationale] strings, and optional [suggestedParameters] that
/// can be applied with one click.
class Recommendation {
  const Recommendation({
    required this.id,
    required this.type,
    required this.severity,
    required this.title,
    required this.rationale,
    this.suggestedParameters,
  });

  /// Stable identifier unique within a generated list.
  final String id;

  /// Classification of the detected issue.
  final RecommendationType type;

  /// Importance level used for ordering.
  final RecommendationSeverity severity;

  /// Short human-readable label shown in the card header.
  final String title;

  /// Expanded explanation of the issue and the suggested change.
  final String rationale;

  /// Pre-computed parameter set to apply with one click, or `null` when no
  /// automatic fix can be calculated.
  final TuningParameters? suggestedParameters;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Recommendation &&
          id == other.id &&
          type == other.type &&
          severity == other.severity;

  @override
  int get hashCode => Object.hash(id, type, severity);

  @override
  String toString() =>
      'Recommendation(id: $id, type: $type, severity: $severity, '
      'title: $title)';
}
